name: Remove package versions
on:
  schedule:
    - cron: '* 8 * * * *'
jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/delete-package-versions@v3
      with:
        min-versions-to-keep: 2
