name: Remove package versions
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: stripethree/gpr-janitor@v2.1.0
      with:
        dryRun: false
        keep-versions: 3
        min-age-days: 20
        packages-to-fetch: 50
        versions-to-fetch: 50
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
